version: '3.9'
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
            target: production
        image: urlencoder_prod
        container_name: urlencoder_prod
        ports:
            - "8000:8000"
        volumes:
            - ./logs:/app/logs
        tty: true
